export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FORECAST_NOT_FOUND = 'FORECAST_NOT_FOUND';
export const FORECAST_LOADING = 'FORECAST_LOADING';
export const FORECAST_ERROR = 'FORECAST_ERROR';